In [30]:
import torch

In [31]:
#Two tensor named as x and y with random values
x=torch.rand(3,3,requires_grad=True) #Pytorch starts to track operations on x to compute the gradient
y=torch.rand(3,3)
print(x)
print(y)

tensor([[0.0323, 0.9391, 0.5427],
        [0.0812, 0.7698, 0.9215],
        [0.8527, 0.8959, 0.0987]], requires_grad=True)
tensor([[0.5540, 0.6740, 0.3370],
        [0.9295, 0.9969, 0.6234],
        [0.3322, 0.5572, 0.2260]])


In [32]:
#Matrix multplication between tensors
Product=torch.matmul(x,y)
print(Product)

tensor([[1.0711, 1.2604, 0.7189],
        [1.0667, 1.3357, 0.7155],
        [1.3380, 1.5229, 0.8681]], grad_fn=<MmBackward0>)


In [33]:
#Autograd
Scalar_value=Product.sum() #Using .sum() to get a scalar value
Scalar_value.backward()
print(x.grad)

tensor([[1.5650, 2.5498, 1.1154],
        [1.5650, 2.5498, 1.1154],
        [1.5650, 2.5498, 1.1154]])


Working of Autograd: Autograd helps to compute the gradients through a graph structure.Pytorch creates a graph with each operation represented by nodes and the entities by edges.Once the graph is computed,a forward pass takes place which finds the output.A forwrd pass is followed by a backward pass which calculates the gradient by traversing the graph in reverse order.The values of gradient are stored in the .grad attribute.

In [34]:
#Creating a 3x1 and 1x3 tensors
a=torch.tensor([[1],[2],[3]])
b=torch.tensor([[5,6,7]])
c=torch.tensor([[1,2,3],[5,6,7],[8,9,0]])
print(a.shape,b.shape,c.shape)

torch.Size([3, 1]) torch.Size([1, 3]) torch.Size([3, 3])


In [35]:
#Using broadcast to add a and b
result=a+b
print(result)
#Multiplying the result with another tensor c (3x3)
resultm=torch.matmul(result,c)
print(resultm)

tensor([[ 6,  7,  8],
        [ 7,  8,  9],
        [ 8,  9, 10]])
tensor([[105, 126,  67],
        [119, 143,  77],
        [133, 160,  87]])


Broadcasting: Broadcasting allows arithmetic operation between tensors of different shapes.
Its only possible under 2 conditions:They are equal, or if one of the dimensions are 1.
In order for the calculation to take place the tensors are expanded:
a=[[1,1,1],[2,2,2],[3,3,3]] b=[[5,6,7],[5,6,7],[5,6,7]] 
then its added element wise, then the tensor c (3x3) is multiplied.

In [36]:
#Creating a tensor with random values with the shape(6x4)
tensor1=torch.rand(6,4)
print(tensor1)

tensor([[0.3446, 0.6164, 0.4031, 0.9764],
        [0.8433, 0.3982, 0.7597, 0.9803],
        [0.2859, 0.2091, 0.1630, 0.5877],
        [0.1818, 0.4238, 0.6531, 0.3784],
        [0.7720, 0.8091, 0.1461, 0.2326],
        [0.1600, 0.8495, 0.7400, 0.0471]])


In [37]:
#Reshaping
tensor_new=tensor1.reshape(3,8)
print(tensor_new)

tensor([[0.3446, 0.6164, 0.4031, 0.9764, 0.8433, 0.3982, 0.7597, 0.9803],
        [0.2859, 0.2091, 0.1630, 0.5877, 0.1818, 0.4238, 0.6531, 0.3784],
        [0.7720, 0.8091, 0.1461, 0.2326, 0.1600, 0.8495, 0.7400, 0.0471]])


Reshaping:Reshaping helps us to change the shape of the tensor without changing the data.The tensors will have the same number of elements before and after reshaping.It organizes the data into the required shape

In [38]:
print(tensor_new[:,:2])

tensor([[0.3446, 0.6164],
        [0.2859, 0.2091],
        [0.7720, 0.8091]])


Slicing:Slicing helps to extract only the required portion of the data by giving the index of the specific rows and columns.We can access and manipulate certain parts of the tensor